routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('home');
});

Route::resource('client', 'ClientController')->except([
    'edit', 'update'
]);

Route::resource('game', 'QuestionController')->except([
    'create', 'edit', 'destroy'
]);
Route::post('game/reset', 'QuestionController@reset');

Route::resource('newsletter', 'NewsletterController')->only([
    'index', 'create', 'store'
]);

Route::resource('config', 'CardController')->only([
    'edit', 'update'
]);

Route::resource('sale', 'SaleController')->only([
    'create','store','edit','update'
]);
Route::put('sale/{id}/{item}/remove','SaleController@removeItem');
Route::put('sale/{id}/{item}/update','SaleController@updateItem');
Route::put('sale/{id}/pay','SaleController@pay');
Route::delete('sale/{id}/cancel','SaleController@cancel');

Route::put('sale/{id}/{item}/{extra}/removeExtra','SaleController@removeExtra');
Route::put('sale/{id}/{item}/{extra}/updateExtra','SaleController@updateExtra');
Route::put('sale/{id}/{item}/addExtra','SaleController@addExtra');

resources/views/home.blade.php
@extends('master')

@section('content')

    <div class="container">
        <div class="row justify-content-around">
            <a href="/" class="btn btn-success btn-lg text-white col-lg-3 col-md-4 col-sm-8 mb-5 mr-3" role="button">
                <i class="fas fa-4x fa-th py-2"></i>
                <h2 class="h5 p-1">Dashboard</h2>
            </a>

            <a class="btn btn-success btn-lg text-white col-lg-3 col-md-4 col-sm-8 mb-5 mr-3" role="button"
               href="/newsletter">
                <i class="far fa-4x fa-newspaper"></i>
                <h2 class="h5 p-1">Newsletter</h2>
            </a>
            <a class="btn btn-success btn-lg text-white col-lg-3 col-md-4 col-sm-8 mb-5 mr-3" role="button"
               href="{{route('sale.create')}}">
                <i class="fas fa-4x fa-shopping-cart m-1"></i>
                <h2 class="h5 p-1">Sale</h2>
            </a>
            <a class="btn btn-success btn-lg text-white col-lg-3 col-md-4 col-sm-8 mb-5 mr-3" role="button"
               href="/client">
                <i class="fas fa-4x fa-users m-1"></i>
                <h2 class="h5 p-1">Clients</h2>
            </a>
            <a class="btn btn-success btn-lg text-white col-lg-3 col-md-4 col-sm-8 mb-5 mr-3" role="button"
               href="/game">
                <i class="fas fa-4x fa-gamepad m-1"></i>
                <h2 class="h5 p-1">Game</h2>
            </a>
            <a class="btn btn-success btn-lg text-white col-lg-3 col-md-4 col-sm-8 mb-5 mr-3" role="button"
               href="/config/1/edit">
                <i class="fas fa-4x fa-cog m-1"></i>
                <h2 class="h5 p-1">Config</h2>
            </a>


        </div>
    </div>

@endsection

resources/views/master.blade.php
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
            integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
            crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
            integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
            crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
            integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
            crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css"
          integrity="sha384-oS3vJWv+0UjzBfQzYUhtDYW+Pj2yciDJxpsK1OYPAYjqT085Qq/1cq5FLXAZQ7Ay" crossorigin="anonymous">
    <title>Jardim da Tia</title>
</head>
<body>

@include('partials.nav')

@yield('messages')

<div class="col-10 mx-auto mt-5">
    @yield('content')
</div>

<div class="mt-5">
    @include('partials.footer')
</div>
</body>
</html>