routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('home');
});

Route::resource('client', 'ClientController')->except([
    'edit', 'update'
]);

Route::resource('game', 'QuestionController')->except([
    'create', 'edit', 'destroy'
]);
Route::post('game/reset', 'QuestionController@reset');

Route::resource('newsletter', 'NewsletterController')->only([
    'index', 'create', 'store'
]);

Route::resource('config', 'CardController')->only([
    'edit', 'update'
]);

Route::resource('sale', 'SaleController')->only([
    'create','store','edit','update'
]);
Route::put('sale/{id}/{item}/remove','SaleController@removeItem');
Route::put('sale/{id}/{item}/update','SaleController@updateItem');
Route::put('sale/{id}/pay','SaleController@pay');
Route::delete('sale/{id}/cancel','SaleController@cancel');

Route::put('sale/{id}/{item}/{extra}/removeExtra','SaleController@removeExtra');
Route::put('sale/{id}/{item}/{extra}/updateExtra','SaleController@updateExtra');
Route::put('sale/{id}/{item}/addExtra','SaleController@addExtra');

app/Http/Controllers/NewsletterController.php
<?php

namespace Uac\SaleSys\Http\Controllers;

use Illuminate\Http\Request;
use Uac\SaleSys\Business\Newsletter;
use Uac\SaleSys\Business\NewsletterHandler;
use Uac\SaleSys\Business\SaleSysFacade;
use Uac\SaleSys\Business\Season;

class NewsletterController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $news = Newsletter::latest()->paginate(4);
        return view('newsletter.index', compact('news'))
            ->with('i', (request()->input('page', 1) - 1) * 4);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $seasons = Season::all();
        return view('newsletter.create', compact('seasons'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param Request $request
     * @param SaleSysFacade $saleSysFacade
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store(Request $request, SaleSysFacade $saleSysFacade)
    {
        $newsletterHandler = $saleSysFacade->getNewsletterHandler();

        $newsletterHandler->createNewsletterForSeason($request['season']);
        return redirect()->route('newsletter.index');
    }
}

resources/views/newsletter/create.blade.php
@extends('master')

@section('messages')
    @if($errors->any())
        <div class="alert alert-danger">
            <strong>Error! </strong> there where some problems with your input.<br>
            <ul>
                @foreach($errors->all() as $error)
                    <li>{{$error}}</li>
                @endforeach
            </ul>
        </div>
    @endif
@endsection

@section('content')

    <div class="jumbotron col-5 mx-auto border border-success py-4">
        <h3 class="text-center">Generate Newsletter</h3>
        <hr>
        <form class="mb-0" action="{{route('newsletter.store')}}" method="post">
            @csrf
            <div class="form-inline justify-content-around">
                <label for="season">Generate the newsletter for the&nbsp;<strong>season</strong>:</label>
                <select id="season" class="custom-select" name="season">
                    @foreach($seasons as $season)
                        <option value="{{$season->id}}">{{$season->name}}</option>
                    @endforeach
                </select>
            </div>
            <div class="row justify-content-between">
                <a href="{{route('newsletter.index')}}" class="btn btn-sm btn-success m-3">Back</a>
                <button type="submit" class="btn btn-sm btn-primary m-3">Generate</button>
            </div>

        </form>
    </div>
@endsection

resources/views/newsletter/index.blade.php
@extends('master')

@section('messages')
    @if($errors->any())
        <div class="alert alert-danger">
            <strong>Error! </strong> there where some problems with your input.<br>
            <ul>
                @foreach($errors->all() as $error)
                    <li>{!!$error!!}</li>
                @endforeach
            </ul>
        </div>
    @endif
    @if($type=Session::get('type'))
        <div class="alert alert-{{$type}}">
            <p>{!!Session::get('message')!!}</p>
        </div>
    @endif
@endsection

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-sm-2">
                <a class="btn btn-sm btn-success" href="{{route('newsletter.create')}}">Generate New Newsletter</a>
            </div>
        </div>
        <div class="row justify-content-around">
            @foreach($news as $new)
                <div class="card text-center p-0 mt-5 mx-auto col-5 border-success">
                    <div class="card-header bg-success text-white">
                        <h5 class="card-title">Newsletter #{{$new->id}} - {{$new->suggestions[0]->season->name}}</h5>
                    </div>
                    <div class="card-body">
                        <ul class="list-group">
                            @foreach($new->suggestions as $suggestion)
                                <li class="list-group-item border-success">{{$suggestion->text}}</li>
                            @endforeach
                        </ul>

                        <hr class="bg-success">

                        @if(!$new->promotions->isEmpty())
                            <div class="bd-example">
                                <div id="newsletter{{$loop->iteration}}" class="carousel slide" data-ride="carousel">
                                    <ol class="carousel-indicators">
                                        @foreach($new->promotions as $promotion)
                                            <li data-target="#newsletter" data-slide-to="{{$loop->iteration}}"
                                                class="bg-success @if ($loop->first) active @endif"></li>
                                        @endforeach
                                    </ol>
                                    <div class="carousel-inner">
                                        @foreach($new->promotions as $promotion)
                                            <div class="carousel-item @if ($loop->first) active @endif">
                                                <img src="{{$promotion->products[0]->image}}"
                                                     class="d-block w-100">
                                                <div class="carousel-caption rounded text-danger"
                                                     style="background-color: rgba(128,128,128,0.25)">
                                                    <p class="h5">{{$promotion->description}}</p>
                                                    <p class="h6">{{$promotion->products[0]->description}}
                                                        with <strong>{{$promotion->percentage*100}}%</strong> Discount
                                                    </p>
                                                    <p class="h6">Before: {{$promotion->products[0]->price}}€
                                                        <strong>Now: {{number_format($promotion->products[0]->price*(1-$promotion->percentage),2)}}
                                                            €</strong>
                                                    </p>
                                                </div>
                                            </div>
                                        @endforeach
                                    </div>
                                    <a class="carousel-control-prev text-success"
                                       href="#newsletter{{$loop->iteration}}"
                                       role="button"
                                       data-slide="prev">
                                        <span><i class="fa fa-2x fa-angle-left " aria-hidden="true"></i></span>
                                        <span class="sr-only">Previous</span>
                                    </a>
                                    <a class="carousel-control-next text-success"
                                       href="#newsletter{{$loop->iteration}}"
                                       role="button"
                                       data-slide="next">
                                        <span><i class="fa fa-2x fa-angle-right " aria-hidden="true"></i></span>
                                        <span class="sr-only">Next</span>
                                    </a>
                                </div>
                            </div>
                        @else
                            <ul class="list-group">
                                <li class="list-group-item border-success">There are currently no promotions at this
                                    season.
                                </li>
                            </ul>
                        @endif
                    </div>

                    <div class="card-footer bg-success text-white">
                        Created at {{ date('M d, o', strtotime($new->publicationDate))}}
                    </div>
                </div>
            @endforeach
        </div>
    </div>
@endsection