routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('home');
});

Route::resource('client', 'ClientController')->except([
    'edit', 'update'
]);

Route::resource('game', 'QuestionController')->except([
    'create', 'edit', 'destroy'
]);
Route::post('game/reset', 'QuestionController@reset');

Route::resource('newsletter', 'NewsletterController')->only([
    'index', 'create', 'store'
]);

Route::resource('config', 'CardController')->only([
    'edit', 'update'
]);

Route::resource('sale', 'SaleController')->only([
    'create','store','edit','update'
]);
Route::put('sale/{id}/{item}/remove','SaleController@removeItem');
Route::put('sale/{id}/{item}/update','SaleController@updateItem');
Route::put('sale/{id}/pay','SaleController@pay');
Route::delete('sale/{id}/cancel','SaleController@cancel');

Route::put('sale/{id}/{item}/{extra}/removeExtra','SaleController@removeExtra');
Route::put('sale/{id}/{item}/{extra}/updateExtra','SaleController@updateExtra');
Route::put('sale/{id}/{item}/addExtra','SaleController@addExtra');

resources/views/game/index.blade.php
@extends('master')

@section('messages')
    @if($errors->any())
        <div class="alert alert-danger">
            <strong>Error! </strong> there where some problems with your input.<br>
            <ul>
                @foreach($errors->all() as $error)
                    <li>{!!$error!!}</li>
                @endforeach
            </ul>
        </div>
    @endif
    @if($type=Session::get('type'))
        <div class="alert alert-{{$type}}">
            <p>{!!Session::get('message')!!}</p>
        </div>
    @endif
@endsection

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <form action="{{route('game.store')}}" method="post">
                @csrf
                <div class="input-group mb-3">
                    <div class="input-group-prepend">
                        <span class="input-group-text bg-success text-white">NIF</span>
                    </div>
                    <input type="number" class="form-control" id="basic-url" aria-describedby="basic-addon3" name="nif"
                           required>
                    <div class="input-group-append">
                        <button class="btn btn-outline-success" type="submit" id="button-addon2">Play</button>
                    </div>
                </div>
            </form>
        </div>

        <div class="row justify-content-center mt-3">
            <form action="game/reset" method="post">
                @csrf
                <input type="submit" class="btn btn-lg btn-warning" value="Reset played status"/>
            </form>
        </div>
    </div>
@endsection

resources/views/game/show.blade.php
@extends('master')

@section('content')

    <div class="mx-auto jumbotron col-md-10 m-0 pb-3">
        <div class="row justify-content-center">
            <h3>{{$question->question}}</h3>
        </div>
        <form action="{{route('game.update',$nif)}}" method="post">
            @method('PUT')
            @csrf

            <div class="form-row justify-content-around mt-3 p-0">
                <div class="btn-group btn-group-toggle col-lg-10 m-1 p-0" data-toggle="buttons">
                    @foreach($question->answers as $answer)
                        <label class="btn btn-outline-primary btn-lg form-check-label col-lg-10 m-1 ">
                            <input class="form-check-input" type="radio" name="answer"
                                   value="{{$answer->id}}"/>{{$answer->answer}}
                        </label>
                    @endforeach
                </div>
            </div>
            <input type="hidden" name="question_id" value="{{$question->id}}">
            <div class="col-lg-10 p-0 mx-auto">
                <div class="form-row my-3 p-0  justify-content-center">
                    <input type="submit" class="btn btn-success" value="Answer"/>
                </div>
            </div>
        </form>
    </div>
@endsection