routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('home');
});

Route::resource('client', 'ClientController')->except([
    'edit', 'update'
]);

Route::resource('game', 'QuestionController')->except([
    'create', 'edit', 'destroy'
]);
Route::post('game/reset', 'QuestionController@reset');

Route::resource('newsletter', 'NewsletterController')->only([
    'index', 'create', 'store'
]);

Route::resource('config', 'CardController')->only([
    'edit', 'update'
]);

Route::resource('sale', 'SaleController')->only([
    'create','store','edit','update'
]);
Route::put('sale/{id}/{item}/remove','SaleController@removeItem');
Route::put('sale/{id}/{item}/update','SaleController@updateItem');
Route::put('sale/{id}/pay','SaleController@pay');
Route::delete('sale/{id}/cancel','SaleController@cancel');

Route::put('sale/{id}/{item}/{extra}/removeExtra','SaleController@removeExtra');
Route::put('sale/{id}/{item}/{extra}/updateExtra','SaleController@updateExtra');
Route::put('sale/{id}/{item}/addExtra','SaleController@addExtra');

app/Http/Controllers/ClientController.php
<?php

namespace Uac\SaleSys\Http\Controllers;

use Uac\SaleSys\Business\Client;
use Illuminate\Http\Request;
use Uac\SaleSys\Business\SaleSysFacade;
use Uac\SaleSys\Exceptions\ApplicationException;

class ClientController extends Controller
{

    const NAME = 'name';
    const EMAIL = 'email';
    const NIF = 'nif';
    const WITH_CARD = 'withCard';

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $clients = Client::latest()->paginate(5);
        return view('client.index', compact('clients'))
            ->with('i', (request()->input('page', 1) - 1) * 5);

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('client.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param Request $request
     * @param SaleSysFacade $saleSysFacade
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store(Request $request, SaleSysFacade $saleSysFacade)
    {
        $clientHandler = $saleSysFacade->getClientHandler();

        $request->validate([
            self::NAME => 'required',
            self::EMAIL => 'required',
            self::NIF => 'required|numeric',
            self::WITH_CARD => 'required'
        ]);

        try {
            $card = $request[self::WITH_CARD] == "true" ? true : false;
            $clientHandler->addClient(
                $request[self::NAME],
                $request[self::EMAIL],
                $request[self::NIF],
                $card
            );
            return redirect()->route('client.index')
                ->with('success', 'New client created successfully');
        } catch (ApplicationException $e) {
            return redirect()->route('client.create')
                ->withInput()
                ->withErrors(['nif' => "Error adding client: " . $e->getMessage()]);
        }

    }

    /**
     * Display the specified resource.
     *
     * @param int $nif
     * @param SaleSysFacade $saleSysFacade
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function show(int $nif, SaleSysFacade $saleSysFacade)
    {
        $clientHandler = $saleSysFacade->getClientHandler();

        $client = $clientHandler->getClient($nif);
        $sales=$client->sales->sortByDesc('updated_at')->take(10);
        return view('client.detail', compact('client','sales'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $nif
     * @param SaleSysFacade $saleSysFacade
     * @return \Illuminate\Http\RedirectResponse
     */
    public function destroy(int $nif, SaleSysFacade $saleSysFacade)
    {
        $clientHandler = $saleSysFacade->getClientHandler();

        $clientHandler->deleteClient($nif);
        return redirect()->route('client.index')
            ->with('success', 'Client deleted successfully');
    }
}

resources/views/client/create.blade.php
@extends('master')

@section('messages')
    @if($errors->any())
        <div class="alert alert-danger">
            <strong>Error! </strong> there where some problems with your input.<br>
            <ul>
                @foreach($errors->all() as $error)
                    <li>{{$error}}</li>
                @endforeach
            </ul>
        </div>
    @endif
@endsection

@section('content')

    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <h3>New Client</h3>
            </div>
        </div>


        <form action="{{route('client.store')}}" method="post">
            @csrf
            <div class="row">
                <div class="col-md-12">
                    <label for="name">Name:</label>
                    <input type="text" name="name" class="form-control" placeholder="Please write your name.."
                           required/>
                </div>
                <div class="col-md-12">
                    <label for="email">Email:</label>
                    <input type="email" name="email" class="form-control" placeholder="Please write your email.."
                           required/>
                </div>
                <div class="col-md-12">
                    <label for="nif">NIF:</label>
                    <input type="number" name="nif" class="form-control" placeholder="Please write your nif.."
                           required/>
                </div>
                <div class="col-md-12">
                    <label for="withCard">Card:</label>
                    <input type="radio" name="withCard" value="true" checked> Yes &nbsp
                    <input type="radio" name="withCard" value="false"> No
                </div>
                <div class="col-md-12">
                    <a href="{{route('client.index')}}" class="btn btn-sm btn-success">Back</a>
                    <button type="submit" class="btn btn-sm btn-primary">Create</button>
                </div>
            </div>
        </form>
    </div>
@endsection

resources/views/client/detail.blade.php
@extends('master')

@section('messages')
    @if($message=Session::get('success'))
        <div class="alert alert-success">
            <p>{{$message}}</p>
        </div>
    @endif
@endsection

@section('content')

    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <h3>{{$client->name}}'s Details</h3>
                <hr>
            </div>
        </div>
        <div class="row">
            <div class="col-xl-3  mx-auto ">
                <div class="card p-0 mt-5 border-success">
                    <div class="card-header bg-success text-center text-white">
                        <h5 class="card-title m-0">Personal Info</h5>
                    </div>
                    <div class="card-body p-0">
                        <div class="form-group row m-0 p-0">
                            <div class="col-4 text-center m-0 p-0 border-right border-success p-2"><strong>Name</strong>
                            </div>
                            <div class="col-8 p-0 m-0 p-2">{{$client->name}}</div>
                        </div>
                        <hr class="bg-success m-0">
                        <div class="form-group row m-0 p-0">
                            <div class="col-4 text-center m-0 p-0 border-right border-success p-2">
                                <strong>Email</strong>
                            </div>
                            <div class="col-8 p-0 m-0 p-2">{{$client->email}}</div>
                        </div>
                        <hr class="bg-success m-0">
                        <div class="form-group row m-0 p-0">
                            <div class="col-4 text-center m-0 p-0 border-right border-success p-2"><strong>NIF</strong>
                            </div>
                            <div class="col-8 p-0 m-0 p-2">{{$client->nif}}</div>
                        </div>

                    </div>
                </div>
            </div>
            @if($client->card)
                <div class="col-xl-2 mx-auto">
                    <div class="card p-0 mt-5  border-success">
                        <div class="card-header bg-success text-center text-white">
                            <h5 class="card-title m-0">Card</h5>
                        </div>
                        <div class="card-body p-0">
                            <div class="form-group row m-0 p-0">
                                <div class="col-8 text-center m-0 p-0 border-right border-success p-2">
                                    <strong>Points</strong>
                                </div>
                                <div class="col-4 p-0 m-0 p-2">{{$client->card->points}}</div>
                            </div>
                            <hr class="bg-success m-0">
                            <div class="form-group row m-0 p-0">
                                <div class="col-8 text-center m-0 p-0 border-right border-success p-2">
                                    <strong>Threshold</strong></div>
                                <div class="col-4 p-0 m-0 p-2">{{$client->card->threshold}}</div>
                            </div>
                        </div>
                    </div>
                </div>
            @endif

            <div class="col-xl-4  mx-auto ">
                <div class="card p-0 mt-5 border-success">
                    <div class="card-header bg-success text-center text-white">
                        <h5 class="card-title m-0">Sales History</h5>
                    </div>
                    <div class="card-body p-0">
                        <table class="table table-striped table-sm border-success col-12 m-0 text-center">
                            <thead class="bg-success text-white">
                            <tr>
                                <th>#</th>
                                <th>Total</th>
                                <th>Date</th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($sales as $sale)
                                <tr>
                                    <td class="align-middle">{{ $loop->iteration }}</td>
                                    <td class="align-middle">{{ $sale->total }} €</td>
                                    <td class="align-middle">{{ $sale->updated_at }}</td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
        <div class="row mt-5">
            <a href="{{route('client.index')}}" class="btn btn-sm btn-success">Back</a>
        </div>
    </div>


@endsection

resources/views/client/index.blade.php
@extends('master')

@section('messages')
    @if($message=Session::get('success'))
        <div class="alert alert-success">
            <p>{{$message}}</p>
        </div>
    @endif
@endsection

@section('content')

    <div class="container">
        <div class="row">
            <div class="col-md-10">
                <h3>Client List</h3>
            </div>
            <div class="col-sm-2">
                <a class="btn btn-sm btn-success" href="{{route('client.create')}}">Create new Client</a>
            </div>
        </div>

        <table class="table table-hover table-sm">
            <thead class="bg-success text-white">
            <tr>
                <th>Nº</th>
                <th>Name</th>
                <th>Email</th>
                <th>NIF</th>
                <th>Card</th>
                <th>Actions</th>
            </tr>
            </thead>
            <tbody>
            @foreach($clients as $client)
                <tr>
                    <td>{{++$i}}</td>
                    <td>{{ $client->name }}</td>
                    <td>{{ $client->email }}</td>
                    <td>{{ $client->nif }}</td>
                    <td>{{ $client->card ? "Yes" : "No" }}</td>
                    <td>
                        <form action="{{route('client.destroy',$client->nif)}}" method="post">
                            <a class="btn btn-sm btn-info" href="{{route('client.show',$client->nif)}}">Details</a>
                            @csrf
                            @method('DELETE')
                            <button type="submit" class="btn btn-sm btn-danger">Delete</button>
                        </form>
                    </td>
                </tr>
            @endforeach
            </tbody>
        </table>
        {!! $clients->links() !!}
    </div>
@endsection